### ISSUE TITLE
proxy error with ODOT private archiver

### ISSUE THREAD

**Issue by kalontrillium** [Trillium-Solutions/gtfs-feed-archive#22]
@ed-g -- When attempting to download a full archive from the ODOT [private portal](https://sites.google.com/a/trilliumtransit.com/operations-manual/client-specific-notes/odot-contract/oregon-odot/gtfsarchivetool), users are consistently recieving this error message. Could you take a look when you have a minute?

Let me know if you need any other info.

http://archive.oregon-gtfs.com/oregon-private-feeds/archive-target
![odot-archive](https://user-images.githubusercontent.com/13739658/49408459-404b9500-f711-11e8-9b27-17472a2eaaff.png)

**Comment by ed-g** [comment]
@KalonThomas note we've moved this repository to 

https://github.com/trilliumtransit/gtfs-api

I've restarted the archive server so it should be up and running.
